---
dist: xenial
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8

# Cache Ansible and Molecule to speed things up
cache:
  - pip

install:
  # Install Ansible, Molecule and docker-py
  - pip install ansible molecule docker ansible-lint flake8

  # Log Docker, Ansible and Molecule version
  - docker --version
  - ansible --version
  - molecule --version

before_script:
  - cd .. && mv ansible-role-epel jgeusebroek.epel && cd jgeusebroek.epel

script:
  # Start test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
